/* Glosario de taller. <Term t="PMS" /> en una lección muestra la definición. */
export interface GlossaryEntry { term: string; alias?: string[]; def: string; cat: "motor" | "electrica" | "electronica" | "chasis" | "fisica" | "general" }

export const GLOSSARY: GlossaryEntry[] = [
  { term: "PMS", alias: ["punto muerto superior", "TDC"], cat: "motor", def: "Punto más alto que alcanza el pistón. Ahí el volumen del cilindro es mínimo. Es la referencia para la puesta a punto y el avance de encendido." },
  { term: "PMI", alias: ["punto muerto inferior", "BDC"], cat: "motor", def: "Punto más bajo que alcanza el pistón. Ahí el volumen del cilindro es máximo." },
  { term: "Carrera", alias: ["stroke"], cat: "motor", def: "Distancia que recorre el pistón entre PMI y PMS. Es el doble del radio del muñón del cigüeñal." },
  { term: "Diámetro", alias: ["bore", "calibre"], cat: "motor", def: "Diámetro interior del cilindro." },
  { term: "Cilindrada", cat: "motor", def: "Volumen total que barren los pistones. Se calcula como π/4 · diámetro² · carrera · número de cilindros. Un '1.6' tiene unos 1.600 cm³." },
  { term: "Relación de compresión", alias: ["ε", "compresión"], cat: "motor", def: "Cuántas veces se achica el volumen del cilindro de PMI a PMS: (volumen barrido + cámara) / cámara. Nafta: ~9 a 13:1. Diesel: ~15 a 20:1." },
  { term: "Cámara de combustión", cat: "motor", def: "Volumen que queda arriba del pistón cuando está en PMS, en la tapa de cilindros." },
  { term: "Aros", alias: ["segmentos", "anillos"], cat: "motor", def: "Anillos elásticos del pistón. Los de compresión sellan la presión; el rascador (aceitero) controla el aceite en las paredes del cilindro." },
  { term: "Bulón", alias: ["perno de pistón"], cat: "motor", def: "Perno que une el pistón con el pie de biela." },
  { term: "Metales", alias: ["cojinetes", "casquillos"], cat: "motor", def: "Cojinetes de deslizamiento de bancada y de biela. El cigüeñal gira sobre una película de aceite a presión, sin tocar el metal." },
  { term: "Muñón", cat: "motor", def: "Parte cilíndrica del cigüeñal que gira dentro de los metales. Los de bancada están en el eje; los de biela, desplazados (manivelas)." },
  { term: "Volante motor", alias: ["volante"], cat: "motor", def: "Disco pesado atornillado al cigüeñal. Guarda energía entre explosiones para suavizar el giro y es donde engrana el burro de arranque." },
  { term: "Árbol de levas", alias: ["eje de levas"], cat: "motor", def: "Eje con levas que abren las válvulas. Gira a la mitad de vueltas que el cigüeñal." },
  { term: "Botador", alias: ["taqué", "buzo"], cat: "motor", def: "Pieza entre la leva y la válvula. Los hidráulicos compensan la luz solos con la presión de aceite." },
  { term: "Cruce de válvulas", alias: ["overlap"], cat: "motor", def: "Momento cerca del PMS de escape en el que admisión y escape están abiertas a la vez. Ayuda a vaciar y llenar mejor el cilindro a altas vueltas." },
  { term: "Motor interferente", cat: "motor", def: "Motor en el que, si se corta la correa de distribución, las válvulas chocan con los pistones. La mayoría de los motores modernos lo son." },
  { term: "Junta de tapa", alias: ["empaquetadura", "junta de culata"], cat: "motor", def: "Junta entre el block y la tapa de cilindros. Sella compresión, agua y aceite. Si se quema, se mezclan o se pierde compresión." },
  { term: "Termostato", cat: "motor", def: "Válvula que mantiene cerrado el paso al radiador hasta que el motor llega a temperatura (suele abrir entre 82 y 95 °C)." },
  { term: "Wastegate", alias: ["válvula de alivio"], cat: "motor", def: "Válvula del turbo que desvía gases de escape para que la turbina no siga acelerando y la presión de soplado no se pase." },
  { term: "Intercooler", cat: "motor", def: "Radiador del aire de admisión: enfría el aire que comprime el turbo para que entre más denso." },
  { term: "Catalizador", cat: "motor", def: "Convierte CO, HC y NOx en CO₂, agua y nitrógeno. El de tres vías necesita mezcla estequiométrica (λ = 1) para trabajar bien." },
  { term: "Lambda", alias: ["λ"], cat: "electronica", def: "Relación entre el aire real y el aire teórico necesario. λ = 1: mezcla ideal (14,7:1 en nafta). λ < 1: rica. λ > 1: pobre." },
  { term: "Estequiométrica", cat: "fisica", def: "Mezcla exacta para quemar todo el combustible con todo el oxígeno. En nafta, 14,7 kg de aire por 1 kg de nafta." },
  { term: "Detonación", alias: ["pistoneo", "knock"], cat: "motor", def: "Combustión descontrolada de la mezcla que todavía no quemó, por presión y temperatura excesivas. Suena como cascabeleo metálico y puede romper pistones." },
  { term: "Avance de encendido", alias: ["avance"], cat: "electronica", def: "Grados de cigüeñal ANTES del PMS en que salta la chispa. La mezcla tarda en quemar, así que se enciende antes para que la presión máxima llegue justo después del PMS." },
  { term: "Dwell", alias: ["tiempo de carga", "ángulo de cierre"], cat: "electronica", def: "Tiempo que la ECU deja circular corriente por el primario de la bobina antes de cortarla para generar la chispa." },
  { term: "Ancho de pulso", alias: ["tiempo de inyección", "pulse width"], cat: "electronica", def: "Milisegundos que la ECU mantiene abierto el inyector. Más ancho de pulso, más nafta." },
  { term: "Ciclo de trabajo", alias: ["duty cycle", "PWM"], cat: "electronica", def: "Porcentaje del tiempo que una señal está activa dentro de cada ciclo. Así se controlan electroválvulas, ventiladores y bombas." },
  { term: "Trim de combustible", alias: ["fuel trim", "STFT", "LTFT", "corrección de mezcla"], cat: "electronica", def: "Corrección que la ECU suma o resta a la nafta según la sonda lambda. Corto plazo (STFT) reacciona rápido; largo plazo (LTFT) aprende. ±10 % es normal." },
  { term: "Lazo cerrado", alias: ["closed loop"], cat: "electronica", def: "Modo en que la ECU corrige la mezcla usando la sonda lambda. En lazo abierto (motor frío, plena carga) usa sólo sus mapas." },
  { term: "Modo de emergencia", alias: ["limp mode", "modo degradado"], cat: "electronica", def: "Estrategia de la ECU cuando un sensor importante falla: usa valores de reemplazo y limita potencia para que llegues al taller." },
  { term: "CKP", alias: ["sensor de cigüeñal", "sensor de rotación"], cat: "electronica", def: "Sensor de posición del cigüeñal. Lee una rueda dentada (típicamente 60-2) y le da a la ECU RPM y posición. Sin CKP, el motor no arranca." },
  { term: "CMP", alias: ["sensor de árbol de levas", "sensor de fase"], cat: "electronica", def: "Sensor de posición del árbol de levas. Le dice a la ECU qué cilindro está en compresión (fase), para la inyección secuencial." },
  { term: "MAP", cat: "electronica", def: "Sensor de presión absoluta del múltiple de admisión. Mide la carga del motor. En ralentí marca poco (vacío) y a fondo casi la presión atmosférica." },
  { term: "MAF", alias: ["caudalímetro", "debímetro"], cat: "electronica", def: "Sensor de masa de aire. Mide cuántos gramos de aire por segundo entran al motor (hilo o película caliente)." },
  { term: "TPS", alias: ["sensor de mariposa"], cat: "electronica", def: "Sensor de posición de la mariposa. Señal de ~0,5 V cerrada a ~4,5 V abierta." },
  { term: "ECT", alias: ["sensor de temperatura de motor"], cat: "electronica", def: "Sensor de temperatura del refrigerante. NTC: más temperatura, menos resistencia." },
  { term: "IAT", alias: ["sensor de temperatura de aire"], cat: "electronica", def: "Sensor de temperatura del aire de admisión. Corrige la mezcla según la densidad del aire." },
  { term: "NTC", cat: "electronica", def: "Termistor de coeficiente negativo: su resistencia baja cuando sube la temperatura." },
  { term: "ECU", alias: ["computadora", "centralita", "ECM", "PCM"], cat: "electronica", def: "Unidad de control electrónico. Lee sensores, decide con sus mapas y maneja actuadores." },
  { term: "DTC", alias: ["código de falla"], cat: "electronica", def: "Código de diagnóstico que guarda la ECU cuando detecta algo fuera de rango (por ej. P0301: falla de encendido en cilindro 1)." },
  { term: "CAN", alias: ["CAN bus", "red CAN"], cat: "electronica", def: "Red por la que se comunican los módulos del auto con dos cables trenzados (CAN-H y CAN-L)." },
  { term: "OBD", alias: ["OBD2", "OBD-II"], cat: "electronica", def: "Diagnóstico de a bordo estandarizado. Conector de 16 pines debajo del tablero." },
  { term: "Caída de tensión", alias: ["voltage drop"], cat: "electrica", def: "Tensión que se 'pierde' en un cable, conexión o masa con corriente circulando. La prueba más útil para encontrar resistencias ocultas." },
  { term: "Masa", alias: ["negativo", "chasis"], cat: "electrica", def: "Camino de regreso de la corriente a la batería a través de la carrocería y el motor." },
  { term: "Relé", alias: ["relay"], cat: "electrica", def: "Interruptor comandado eléctricamente: una corriente chica (85-86) maneja una grande (30-87)." },
  { term: "Torque", alias: ["par", "momento"], cat: "fisica", def: "Fuerza de giro: fuerza × brazo de palanca. Se mide en N·m." },
  { term: "Potencia", cat: "fisica", def: "Trabajo por unidad de tiempo. En el motor: torque × velocidad de giro. P[kW] = M[N·m] · n[rpm] / 9550. 1 CV ≈ 0,735 kW." },
  { term: "Presión", cat: "fisica", def: "Fuerza repartida en un área: p = F/A. 1 bar = 100.000 Pa ≈ 14,5 psi ≈ la presión atmosférica a nivel del mar." },
  { term: "Presión absoluta", cat: "fisica", def: "Presión medida desde el vacío total. La manométrica (la de las cubiertas) se mide desde la atmosférica." },
  { term: "Resonancia", cat: "fisica", def: "Cuando algo se excita a su frecuencia natural, la vibración crece muchísimo. Por eso existen amortiguadores y dámper de cigüeñal." },
  { term: "Viscosidad", cat: "fisica", def: "Resistencia de un fluido a fluir. En aceites, el número SAE: 5W-30 es fluido en frío (5W) y se comporta como un 30 en caliente." },
  { term: "Rendimiento", alias: ["eficiencia", "η"], cat: "fisica", def: "Qué parte de la energía que entra sale como trabajo útil. Un motor naftero convierte en movimiento sólo entre 25 y 38 % de la energía de la nafta." },
  { term: "Silent block", alias: ["buje", "soporte de motor"], cat: "chasis", def: "Pieza de goma con metal que une componentes absorbiendo vibraciones (soportes de motor, bujes de parrilla)." },
  { term: "Convergencia", alias: ["toe"], cat: "chasis", def: "Cuánto apuntan las ruedas hacia adentro o afuera vistas desde arriba. Mal regulada, come cubiertas por los bordes." },
  { term: "Camber", alias: ["caída"], cat: "chasis", def: "Inclinación de la rueda vista de frente." },
  { term: "Caster", alias: ["avance de dirección"], cat: "chasis", def: "Inclinación del eje de la dirección visto de costado. Hace que el volante vuelva solo al centro." },
  { term: "RTO", alias: ["revisión técnica", "VTV"], cat: "general", def: "Revisión técnica vehicular obligatoria. En Mendoza se la conoce como RTO; en otras provincias, VTV." },
  { term: "GNC", cat: "general", def: "Gas natural comprimido. Se guarda a ~200 bar en el tubo y un reductor lo baja a la presión de trabajo para inyectarlo." },
  { term: "Reductor", alias: ["regulador de GNC"], cat: "general", def: "Equipo de GNC que baja la presión del gas desde el tubo a la de trabajo y lo calienta con el agua del motor para que no se congele." },
];
