/* Preguntas de la Parte 0 — Antes de arrancar */
import type { Question } from "./index";

const q: Record<string, Question[]> = {
  "arranque-sistema": [
    {
      q: "Un cliente dice que su auto «tironea» al acelerar. ¿Qué es lo más sensato antes de cambiar nada?",
      opts: [
        "Cambiar las bujías, que es lo más común",
        "Cambiar el embrague, porque si tironea es que patina",
        "Pensar qué sistemas pueden producir ese síntoma (motor, tren motriz, chasis) y juntar datos para descartar",
        "Borrar los códigos de falla y ver si se arregla solo",
      ],
      correct: 2,
      explain: "Un tirón puede venir del motor (bujía, bobina, inyector), del tren motriz (embrague que patina) o del chasis (un soporte de motor roto). Pensar en sistemas y juntar datos evita cambiar piezas a ciegas. Borrar códigos sin leerlos es tirar información.",
      topic: "Sistemas",
    },
    {
      q: "¿Cuál de estos NO es un vehículo automotor?",
      opts: [
        "Un tranvía",
        "Una moto",
        "Un colectivo",
        "Una pick-up 4x4",
      ],
      correct: 0,
      explain: "Un automotor se mueve con motor propio por calles y rutas, sin rieles. El tranvía va sobre rieles, así que queda afuera aunque tenga motor.",
      topic: "Definición",
    },
    {
      q: "En un auto con tracción delantera y motor transversal, ¿dónde está el diferencial?",
      opts: [
        "Atrás, en una «bocha» entre las ruedas traseras",
        "En cada rueda, uno por rueda",
        "No tiene: las ruedas giran siempre a la misma velocidad",
        "En un solo bloque con la caja de cambios, al lado del motor",
      ],
      correct: 3,
      explain: "En la tracción delantera la caja y el diferencial vienen juntos (se suele llamar transeje) y del diferencial salen los dos semiejes a las ruedas delanteras. La «bocha» trasera es de la tracción trasera. Y diferencial siempre hay: sin él las ruedas no podrían girar distinto en una curva.",
      topic: "Tracción",
    },
    {
      q: "De toda la energía que hay en la nafta que cargás, ¿qué parte llega más o menos a las ruedas de un auto naftero en ciudad?",
      opts: [
        "Alrededor del 90 %",
        "Alrededor del 15 %",
        "Alrededor del 60 %",
        "Menos del 1 %",
      ],
      correct: 1,
      explain: "En ciudad llega más o menos un 15 % (en ruta, un 25 %). La mayor parte se va como calor por el escape y por el radiador, más rozamientos, bombeo y accesorios. El 85–90 % es lo que llega en un auto eléctrico, desde la batería.",
      topic: "Energía",
    },
    {
      q: "Prendés el aire acondicionado en un semáforo y el ralentí sube solo un poco. ¿Qué está pasando?",
      opts: [
        "La ECU compensa la fuerza que le pide el compresor del aire para que el motor no se pare",
        "Una falla del sensor de temperatura",
        "El aire acondicionado tiene poco gas",
        "La batería se está descargando",
      ],
      correct: 0,
      explain: "Es un ejemplo de sistemas conectados: el compresor (confort) le roba fuerza al motor, y la ECU (electrónica) sube el ralentí para compensar. Además, el condensador calienta el radiador y el electroventilador arranca antes.",
      topic: "Sistemas",
    },
    {
      q: "Un auto se queda sin batería y no hace nada al girar la llave. ¿Qué sistema mirás primero?",
      opts: [
        "Tren motriz",
        "Chasis",
        "Eléctrico",
        "Carrocería",
      ],
      correct: 2,
      explain: "Sin ningún ruido al girar la llave, lo primero es la red de 12 V: tensión de batería, bornes sulfatados, masas y el burro de arranque.",
      topic: "Diagnóstico",
    },
    {
      q: "¿Qué diferencia a un auto monocasco de una pick-up con chasis de largueros?",
      opts: [
        "El monocasco no tiene estructura: todo cuelga de los paragolpes",
        "En el monocasco la carrocería misma es la estructura; en la pick-up, dos largueros de acero cargan todo y la cabina va atornillada encima",
        "Son lo mismo con distinto nombre",
        "El chasis de largueros es más liviano y por eso lo usan los autos chicos",
      ],
      correct: 1,
      explain: "Casi todos los autos son monocasco: más livianos y con mejor absorción de choques. Las pick-ups y camiones usan chasis de largueros porque aguantan mejor la carga, el remolque y el maltrato.",
      topic: "Carrocería",
    },
    {
      q: "Un naftero gasta 63 kWh de nafta cada 100 km y un eléctrico parecido gasta 15 kWh de batería. Si a las ruedas les llega casi lo mismo, ¿qué explica la diferencia?",
      opts: [
        "El eléctrico es más liviano",
        "El eléctrico no tiene rozamiento en las cubiertas",
        "Es un error: tendrían que gastar lo mismo",
        "El naftero pierde la mayor parte de la energía como calor; el eléctrico convierte en movimiento cerca del 85–90 %",
      ],
      correct: 3,
      explain: "Las ruedas necesitan más o menos la misma energía en los dos casos (aire, rodadura, frenos). La diferencia está en el rendimiento: el motor de combustión es una máquina térmica y tira al aire la mayor parte de lo que quema.",
      topic: "Energía",
    },
  ],

  "arranque-seguridad": [
    {
      q: "Levantaste la trompa con el crique carrito para cambiar las pastillas. ¿Qué falta antes de meter las manos debajo del auto?",
      opts: [
        "Nada, el crique carrito es hidráulico y es seguro",
        "Caballetes en los puntos de levante, ruedas de atrás calzadas, prueba del empujón",
        "Poner un par de ladrillos debajo del zócalo",
        "Dejar el motor en marcha por si hay que moverlo",
      ],
      correct: 1,
      explain: "El crique levanta; el caballete sostiene. Un crique hidráulico puede perder presión de golpe y el auto cae en un cuarto de segundo. Los ladrillos se parten bajo carga. Y la rueda sacada debajo del zócalo es un buen seguro extra.",
      topic: "Levantar el auto",
    },
    {
      q: "Vas a levantar la COLA del auto. ¿Dónde van las calzas?",
      opts: [
        "En las ruedas de adelante, porque el freno de mano frena las de atrás y esas van a quedar en el aire",
        "En las ruedas de atrás",
        "No hacen falta si pusiste el freno de mano",
        "Debajo del crique",
      ],
      correct: 0,
      explain: "El freno de mano actúa sobre las ruedas traseras. Si levantás la cola, esas ruedas quedan colgando y el freno de mano no sostiene nada: hay que calzar las de adelante, que quedan en el piso.",
      topic: "Levantar el auto",
    },
    {
      q: "Vas a sacar la batería. ¿En qué orden desconectás?",
      opts: [
        "Primero el positivo, después el negativo",
        "Da lo mismo",
        "Primero el negativo, después el positivo",
        "Los dos a la vez con una pinza",
      ],
      correct: 2,
      explain: "Toda la carrocería está conectada al negativo. Si aflojás el positivo con el negativo puesto y la llave toca la chapa, hacés un cortocircuito de cientos de amperes. Con el negativo afuera, el circuito queda abierto. Para conectar, al revés: positivo primero, negativo último.",
      topic: "Batería",
    },
    {
      q: "El motor está caliente y el depósito de refrigerante está bajo. ¿Qué hacés?",
      opts: [
        "Abro la tapa rápido para que no se escape la presión",
        "Espero a que el motor se enfríe antes de abrir; si no hay más remedio, trapo grueso, de costado y primero libero la presión hasta el primer tope",
        "Le echo agua fría arriba del radiador para enfriarlo",
        "Lo dejo andando y abro la tapa con el motor en marcha",
      ],
      correct: 1,
      explain: "El sistema está a 1–1,5 bar y el refrigerante a más de 100 °C sin hervir gracias a esa presión. Al abrir en caliente, hierve de golpe y sale un chorro de vapor y agua hirviendo. Agua fría sobre un motor caliente puede rajar piezas.",
      topic: "Refrigeración",
    },
    {
      q: "Estás trabajando cerca del radiador con el motor recién apagado y la llave sacada. ¿Qué peligro todavía existe?",
      opts: [
        "Ninguno: con la llave sacada no funciona nada",
        "La bobina puede dar chispa",
        "La bomba de nafta puede arrancar",
        "El electroventilador puede arrancar solo para enfriar el motor",
      ],
      correct: 3,
      explain: "En muchos autos el electroventilador lo comanda la temperatura, no la llave, y sigue funcionando un rato después de apagar. Si vas a trabajar cerca, desenchufá su ficha.",
      topic: "Motor en marcha",
    },
    {
      q: "Para hacer andar el motor dentro del garaje un rato, ¿qué es imprescindible?",
      opts: [
        "Nada, el catalizador limpia los gases",
        "Prender un ventilador de pie",
        "Portón abierto o una manguera que saque el escape afuera: el monóxido de carbono no tiene olor y mata",
        "Que el motor esté caliente",
      ],
      correct: 2,
      explain: "El monóxido de carbono (CO) es invisible, sin olor y se acumula en lugares cerrados; sobre todo en frío, el catalizador todavía no trabaja. Dolor de cabeza, mareo y sueño son síntomas de intoxicación: afuera ya.",
      topic: "Motor en marcha",
    },
    {
      q: "En un auto híbrido ves unos cables gruesos de color naranja. ¿Qué significa?",
      opts: [
        "Son de alta tensión (de cientos de volts): no se tocan sin capacitación, EPP específico y el procedimiento del fabricante",
        "Son los cables de la batería de 12 V, se pueden desconectar como siempre",
        "Son los de las bujías",
        "Son cables de datos de la red CAN",
      ],
      correct: 0,
      explain: "Por norma, los cables de alta tensión de híbridos y eléctricos son naranjas, y trabajan entre 200 y más de 800 V de continua. Eso sí puede matar. Aunque el auto esté apagado, puede haber tensión.",
      topic: "Alta tensión",
    },
    {
      q: "Cambiaste el refrigerante y quedó una bandeja con el líquido viejo en el patio. ¿Por qué es un problema?",
      opts: [
        "Porque se evapora y mancha el piso",
        "No es problema, el refrigerante es agua con colorante",
        "Porque es inflamable como la nafta",
        "Porque el etilenglicol es dulce y tóxico: perros, gatos y chicos lo pueden tomar",
      ],
      correct: 3,
      explain: "El refrigerante tiene un sabor dulce que atrae a los animales, y poca cantidad puede matar a una mascota. Se junta en un bidón cerrado y se lleva a un punto de recolección, igual que el aceite usado.",
      topic: "Fluidos",
    },
  ],

  "arranque-unidades": [
    {
      q: "La etiqueta de la puerta dice 2,2 bar y en la gomería te preguntan «¿a cuánto?». ¿Qué les decís?",
      opts: [
        "22 psi",
        "32 psi",
        "2,2 psi",
        "220 psi",
      ],
      correct: 1,
      explain: "1 bar ≈ 14,5 psi, así que 2,2 × 14,5 ≈ 32 psi. Leer la escala equivocada del manómetro (2,2 psi o 32 bar) es uno de los errores más comunes.",
      topic: "Presión",
    },
    {
      q: "Un manual viejo dice que un tornillo va a «8 kgm». ¿A cuántos N·m ajustás el torquímetro?",
      opts: [
        "8 N·m",
        "Unos 800 N·m",
        "Unos 11 N·m",
        "Unos 80 N·m",
      ],
      correct: 3,
      explain: "1 kgf·m = 9,81 N·m ≈ 10 N·m. Entonces 8 kgf·m ≈ 78 N·m. La regla mental «multiplicá por 10» te deja a un 2 % del valor exacto.",
      topic: "Torque",
    },
    {
      q: "Un manual norteamericano pide 100 lb·in para un tornillo chico. ¿Qué pasa si lo apretás a 100 lb·ft?",
      opts: [
        "Nada, es lo mismo",
        "Queda flojo",
        "Queda 12 veces más apretado de lo que corresponde: probablemente lo pasás de rosca o lo cortás",
        "Queda un 10 % más apretado",
      ],
      correct: 2,
      explain: "Un pie tiene 12 pulgadas, así que 1 lb·ft = 12 lb·in. 100 lb·in son apenas unos 11 N·m; 100 lb·ft son unos 136 N·m. Leé dos veces la unidad en los manuales yanquis.",
      topic: "Torque",
    },
    {
      q: "Con el contacto puesto y el motor parado, en Mendoza, el scanner muestra el MAP en 93 kPa. ¿Qué concluís?",
      opts: [
        "Está bien: el MAP mide presión absoluta, y con el motor parado mide la atmosférica del lugar",
        "El sensor está roto: con el motor parado tendría que marcar 0",
        "Hay una pérdida de vacío",
        "La mariposa está trabada abierta",
      ],
      correct: 0,
      explain: "El MAP cuenta desde el vacío total (presión absoluta). Con el motor parado, en el múltiple hay presión atmosférica: unos 101 kPa a nivel del mar y unos 92–93 kPa en el Gran Mendoza.",
      topic: "Relativa y absoluta",
    },
    {
      q: "Un auto tiene 150 CV. ¿Cuántos kW son, más o menos?",
      opts: [
        "Unos 200 kW",
        "Unos 150 kW",
        "Unos 75 kW",
        "Unos 110 kW",
      ],
      correct: 3,
      explain: "1 CV ≈ 0,735 kW: los kW son más o menos ¾ de los CV. 150 × 0,735 ≈ 110 kW.",
      topic: "Potencia",
    },
    {
      q: "El tester marca «2,5» con una «k» al lado en la escala de ohms, midiendo un sensor de temperatura. ¿Cuánto es?",
      opts: [
        "2,5 Ω",
        "2.500 Ω",
        "250 Ω",
        "2.500.000 Ω",
      ],
      correct: 1,
      explain: "k es kilo: × 1.000. 2,5 kΩ = 2.500 Ω, un valor típico de un sensor de temperatura NTC a unos 20 °C. Si fuera M (mega), serían 2.500.000 Ω.",
      topic: "Prefijos",
    },
    {
      q: "El motor pasa de 20 °C a 90 °C. ¿Cuánto subió en °F?",
      opts: [
        "126 °F",
        "70 °F",
        "158 °F",
        "194 °F",
      ],
      correct: 0,
      explain: "Una diferencia de temperatura se convierte multiplicando por 1,8, sin el +32: 70 °C × 1,8 = 126 °F. (Las temperaturas sí llevan el +32: 90 °C son 194 °F y 20 °C son 68 °F; la resta da 126 °F.)",
      topic: "Temperatura",
    },
    {
      q: "Convertís 32 psi a bar y la calculadora da 2,206317. ¿Cómo lo anotás?",
      opts: [
        "2,206317 bar",
        "2 bar",
        "2,2 bar",
        "2,21 psi",
      ],
      correct: 2,
      explain: "El dato original (32 psi) tiene dos cifras significativas; inventarle seis decimales es fingir una precisión que no existe. 2,2 bar es lo que de verdad sabés.",
      topic: "Redondeo",
    },
  ],

  "arranque-mendoza": [
    {
      q: "Medís la compresión de un motor naftero sano en el Gran Mendoza. El dato de fábrica es 12,5 bar. ¿Qué esperás ver?",
      opts: [
        "Algo menos, cerca de 11,4 bar, pero parejo entre cilindros",
        "Exactamente 12,5 bar en los cuatro cilindros",
        "Más de 12,5 bar porque el aire es más seco",
        "La mitad, unos 6 bar",
      ],
      correct: 0,
      explain: "El dato de fábrica es a nivel del mar. En Mendoza el cilindro arranca la compresión con aire a menos presión y el resultado da un 8–9 % menos. Lo que no cambia con la altura es la regla: menos de 10–15 % de diferencia entre cilindros.",
      topic: "Altura",
    },
    {
      q: "¿Por qué un motor turbo pierde mucha menos potencia que uno atmosférico al subir a Uspallata?",
      opts: [
        "Porque el turbo usa otro combustible",
        "Porque el turbo enfría el motor",
        "No es así: pierden lo mismo",
        "Porque el turbo comprime el aire antes de que entre al cilindro y la ECU mantiene la presión de soplado",
      ],
      correct: 3,
      explain: "El atmosférico llena los cilindros con el aire que encuentra y pierde más o menos 1 % cada 100 m. El turbo gira más rápido para llegar a la misma presión absoluta en el múltiple y compensa casi todo hasta los 2.000–2.500 m.",
      topic: "Altura",
    },
    {
      q: "Un auto carburado que andaba bien en Mendoza larga humo negro y ensucia bujías en Las Cuevas. ¿Por qué?",
      opts: [
        "Porque la nafta de montaña es de peor calidad",
        "Porque el carburador dosifica según la depresión del aire y con aire menos denso la mezcla se enriquece",
        "Porque el frío le cierra el cebador",
        "Porque la bomba de nafta empuja más en altura",
      ],
      correct: 1,
      explain: "Un carburador no «sabe» que hay menos oxígeno: el aire menos denso desacomoda la cuenta y la mezcla queda rica. La inyección electrónica, en cambio, corrige sola con el MAP o el MAF y la sonda lambda. Los carburados que viven en altura se achiclan.",
      topic: "Mezcla",
    },
    {
      q: "Inflaste las cubiertas en frío a 32 psi en Mendoza. Llegás a Las Cuevas y, con las cubiertas todavía frías, el manómetro marca unos 35 psi. ¿Qué hacés?",
      opts: [
        "Nada raro: adentro hay el mismo aire, pero afuera la presión atmosférica es menor y el manómetro marca la diferencia",
        "Las desinflo a 32 psi porque están pasadas",
        "Busco una pinchadura",
        "Las inflo más para compensar el frío",
      ],
      correct: 0,
      explain: "El manómetro mide presión relativa: adentro menos afuera. Al subir, afuera empuja menos y la lectura sube unos 3 psi, sin que cambie el aire de adentro. Al volver a Mendoza, vuelve a 32. Si vas a quedarte días arriba, recién ahí calibrás en frío allá.",
      topic: "Cubiertas",
    },
    {
      q: "Bajando de Las Cuevas el pedal de freno se pone largo y casi llega al piso. ¿Cuál es la causa más probable y qué hacés?",
      opts: [
        "Pastillas nuevas que todavía no asentaron; sigo igual",
        "Falta de aire en las cubiertas; las inflo",
        "Líquido de frenos que hirvió por el calor (seguramente viejo y con humedad): paro en un lugar seguro, dejo enfriar y después bajo con freno motor",
        "Es el ABS funcionando; es normal",
      ],
      correct: 2,
      explain: "El líquido de frenos absorbe humedad con el tiempo y su punto de ebullición baja. En una bajada larga frenando todo el tiempo, hierve, se forma vapor y el pedal se va al piso. Se previene con líquido nuevo y bajando con un cambio puesto.",
      topic: "Montaña",
    },
    {
      q: "¿Por qué conviene bajar la cordillera con un cambio puesto y no en punto muerto?",
      opts: [
        "Porque en punto muerto se gasta la caja",
        "Porque el motor frena el auto (freno motor) y, encima, con el pie fuera del acelerador la ECU corta la inyección y no se consume nafta",
        "Porque en punto muerto el auto no dobla",
        "Da lo mismo",
      ],
      correct: 1,
      explain: "Con un cambio puesto el motor hace de freno y los frenos quedan frescos para cuando hacen falta. Y en un auto con inyección, en desaceleración la ECU corta el combustible: consumo cero. En punto muerto, el motor sigue en ralentí gastando.",
      topic: "Montaña",
    },
    {
      q: "Viajás a Penitentes en invierno y el refrigerante del auto es agua de la canilla. ¿Cuál es el riesgo?",
      opts: [
        "Ninguno, el motor calienta el agua",
        "Que el motor consuma más nafta",
        "Que se descargue la batería",
        "Que el agua se congele de noche, se expanda y parta el block o el radiador",
      ],
      correct: 3,
      explain: "El agua al congelarse se expande alrededor de un 9 %, con fuerza suficiente para rajar fundiciones. Un refrigerante al 50 % protege hasta unos −35 °C, y además sube el punto de ebullición.",
      topic: "Invierno",
    },
    {
      q: "¿Por qué en Mendoza las baterías suelen «morir» en verano o la primera mañana fría después del verano?",
      opts: [
        "Porque el frío las congela",
        "Porque en verano se usan menos las luces",
        "Porque el calor acelera la corrosión interna y la pérdida de agua; el daño se hace en verano y se nota cuando el motor pide más",
        "Porque el GNC descarga la batería",
      ],
      correct: 2,
      explain: "El calor es lo que más castiga a una batería de plomo. Con 40 °C afuera y mucho más en el vano motor, las placas se degradan. Muchas terminan de fallar en la primera mañana fría, cuando el aceite espeso pide más corriente de arranque.",
      topic: "Calor",
    },
  ],
};

export default q;
