/* Preguntas de la Parte 1 "Física para el taller": mecánica y fluidos. */
import type { Question } from "./index";

const q: Record<string, Question[]> = {
  "fis-palanca": [
    {
      q: "Un bulón de rueda pide 110 N·m para aflojarse. Con una llave de 25 cm empujando a 90°, ¿cuánta fuerza necesitás como mínimo?",
      opts: ["27,5 N", "275 N", "440 N", "2.750 N"],
      correct: 2,
      explain: "T = F · d → F = T / d = 110 N·m / 0,25 m = 440 N, como colgarte unos 45 kg de la punta. Con una llave cruz de 40 cm bajaría a 275 N.",
      topic: "Torque",
    },
    {
      q: "Empujás la llave en diagonal, a 30° del mango en lugar de 90°. ¿Qué pasa con el torque que hacés?",
      opts: ["Es el mismo, la fuerza es la misma", "Se reduce a la mitad, porque el brazo efectivo es L · sen 30°", "Aumenta, porque empujás más cerca del bulón", "Se reduce a cero"],
      correct: 1,
      explain: "El torque usa la distancia perpendicular entre el eje y la línea de la fuerza: d = L · sen α. Con 30°, sen 30° = 0,5, así que perdés la mitad del torque. Por eso hay que empujar perpendicular al mango.",
      topic: "Torque",
    },
    {
      q: "El pedal de freno tiene el pivote arriba, tu pie abajo y la varilla de la bomba enganchada entre ambos, cerca del pivote. ¿Qué tipo de palanca es?",
      opts: ["De 1er género: el apoyo está en el medio", "De 2do género: la carga está entre el apoyo y la fuerza", "De 3er género: la fuerza está entre el apoyo y la carga", "No es una palanca, es un pistón"],
      correct: 1,
      explain: "Apoyo en una punta (pivote), tu fuerza en la otra (pie) y la carga en el medio (varilla): 2do género. Siempre multiplica fuerza; en un pedal típico, ×4 a ×6.",
      topic: "Palancas",
    },
    {
      q: "Un motor da 200 N·m a 3.000 rpm. ¿Qué potencia entrega en ese punto?",
      opts: ["≈ 6,3 kW", "≈ 63 kW", "≈ 600 kW", "≈ 20 kW"],
      correct: 1,
      explain: "P[kW] = T · n / 9.549 = 200 × 3.000 / 9.549 ≈ 62,8 kW (unos 85 CV). Es P = T · ω con ω = 2π · n / 60.",
      topic: "Potencia",
    },
    {
      q: "Engrasaste la rosca de un bulón que el manual especifica 'en seco' y lo apretaste al torque indicado. ¿Qué pasó?",
      opts: [
        "Nada, el torquímetro asegura la fuerza correcta",
        "Quedó más flojo, porque la grasa resbala",
        "Quedó con bastante más precarga de la prevista: con menos rozamiento, más torque se convierte en estiramiento",
        "La rosca se barre siempre",
      ],
      correct: 2,
      explain: "Alrededor del 90 % del torque se va en rozamiento (bajo la cabeza y en los filetes). Si lo bajás con grasa, con el mismo torque la precarga puede subir un 30–40 % y el bulón se estira de más.",
      topic: "Rosca",
    },
    {
      q: "¿Por qué la potencia máxima de un motor aparece a más rpm que el torque máximo?",
      opts: [
        "Porque a altas vueltas el torque sube",
        "Porque potencia = torque × velocidad de giro: aunque el torque empiece a bajar, las vueltas suben más rápido",
        "Porque el turbo sólo funciona a altas vueltas",
        "Es casualidad, depende del motor",
      ],
      correct: 1,
      explain: "P = T · ω. Pasado el pico de torque, T baja de a poco, pero ω sigue subiendo proporcionalmente; el producto sigue creciendo hasta que la caída de torque le gana.",
      topic: "Potencia",
    },
    {
      q: "La ECU detecta una falla de encendido en el cilindro 3 sin ningún sensor en ese cilindro. ¿Cómo lo hace?",
      opts: [
        "Mide la tensión de la bujía",
        "Con el sensor de cigüeñal: mide la aceleración angular después de cada explosión; si un cilindro no empuja, el cigüeñal se frena un poco en esa parte de la vuelta",
        "Con la sonda lambda, que detecta qué cilindro falló",
        "No puede, sólo lo detecta el mecánico",
      ],
      correct: 1,
      explain: "Es la segunda ley de Newton en rotación: sin torque del cilindro 3, la velocidad angular cae en ese tramo. El CKP mide el tiempo entre dientes y la ECU guarda P0303.",
      topic: "Electrónica",
    },
  ],

  "fis-resistencia": [
    {
      q: "Un tornillo con 58 mm² de sección resistente soporta 29.000 N. ¿Cuál es su tensión de tracción?",
      opts: ["50 MPa", "500 MPa", "1.682 MPa", "5.000 MPa"],
      correct: 1,
      explain: "σ = F / A = 29.000 N / 58 mm² = 500 N/mm² = 500 MPa. Un MPa es exactamente un newton por milímetro cuadrado.",
      topic: "Tensión",
    },
    {
      q: "¿Qué significa la marca '10.9' en la cabeza de un tornillo?",
      opts: [
        "Que mide 10 mm de diámetro y 9 cm de largo",
        "Rm ≈ 1.000 MPa y límite elástico ≈ 90 % de eso (≈ 900 MPa)",
        "Que soporta 10,9 toneladas",
        "La fecha de fabricación",
      ],
      correct: 1,
      explain: "Primer número × 100 = resistencia a la tracción en MPa; segundo × 10 = porcentaje de esa resistencia donde empieza la fluencia. Un 8.8 fluye con un 30 % menos de tensión que un 10.9.",
      topic: "Tornillos",
    },
    {
      q: "Cambiás la junta de tapa y reutilizás los tornillos TTY 'porque estaban bien'. ¿Cuál es el problema?",
      opts: [
        "Ninguno, si no están oxidados",
        "Ya fueron llevados más allá del límite elástico: quedaron estirados y el mismo ángulo los lleva todavía más a la zona plástica; pueden cortarse o no dar la precarga",
        "Que se aflojan por la vibración",
        "Que el torquímetro no los detecta",
      ],
      correct: 1,
      explain: "Los TTY se aprietan por ángulo hasta apenas pasar la fluencia. Al soltarlos quedan con deformación permanente; cada reuso los acerca a la estricción y a la rotura. Salvo que el manual permita medir y reutilizar, van nuevos.",
      topic: "TTY",
    },
    {
      q: "Según la Ley de Hooke, ¿cuánto se estira un tornillo de acero de 100 mm que trabaja a 420 MPa? (E = 210.000 MPa)",
      opts: ["0,02 mm", "0,2 mm", "2 mm", "4,2 mm"],
      correct: 1,
      explain: "ε = σ / E = 420 / 210.000 = 0,002 (0,2 %). Δl = 0,002 × 100 mm = 0,2 mm. En esas dos décimas está guardada toda la fuerza de apriete: el tornillo trabaja como un resorte.",
      topic: "Hooke",
    },
    {
      q: "Un semieje se cortó en una salida tranquila. La fractura tiene una zona lisa con 'marcas de playa' y una zona chica rugosa. ¿Qué fue?",
      opts: [
        "Una sobrecarga de golpe (un pozo)",
        "Fatiga: una fisura que avanzó despacio durante muchos ciclos y al final la sección que quedaba se cortó",
        "Corrosión por agua",
        "Un defecto de fabricación que se nota sólo con rayos X",
      ],
      correct: 1,
      explain: "Las marcas de playa muestran el avance lento de la fisura con cada ciclo de carga; la zona rugosa es la rotura final. Es la firma típica de la fatiga.",
      topic: "Fatiga",
    },
    {
      q: "Un semieje de Ø 24 mm se reemplaza por uno de Ø 30 mm del mismo material. ¿Cuánto más torque aguanta aproximadamente?",
      opts: ["25 % más", "56 % más", "Casi el doble", "Lo mismo, depende del material"],
      correct: 2,
      explain: "A torsión, τ = T / Wt con Wt = π · d³ / 16. (30/24)³ ≈ 1,95: casi el doble. En flexión y torsión el diámetro va al cubo.",
      topic: "Torsión",
    },
    {
      q: "¿Por qué un bulón de rueda que anduvo flojo termina cortándose aunque la carga sea la de siempre?",
      opts: [
        "Porque se oxida más",
        "Porque sin precarga la llanta se mueve sobre la maza y el bulón recibe la carga variable completa a corte y flexión en cada vuelta: fatiga",
        "Porque se calienta y se ablanda",
        "Porque la rosca se estira por el peso del auto",
      ],
      correct: 1,
      explain: "Con su precarga, la unión trabaja por rozamiento y el bulón casi no siente las variaciones. Flojo, cada vuelta lo flexiona y lo corta un poco: miles de ciclos después, se rompe por fatiga.",
      topic: "Fatiga",
    },
  ],

  "fis-rozamiento": [
    {
      q: "Un bloque de 10 kg está quieto sobre una mesa (μs = 0,3). Lo empujás horizontalmente con 10 N. ¿Cuánto vale el rozamiento?",
      opts: ["29,4 N (μs · N)", "10 N", "0 N", "3 N"],
      correct: 1,
      explain: "Mientras está quieto, el rozamiento estático iguala la fuerza que aplicás, hasta un tope de μs · N = 0,3 × 98 ≈ 29 N. Con 10 N, el rozamiento vale 10 N y el bloque no se mueve.",
      topic: "Estático",
    },
    {
      q: "¿Por qué un auto con ABS frena, en asfalto, en menos distancia que uno con las ruedas bloqueadas?",
      opts: [
        "Porque el ABS aprieta más fuerte las pastillas",
        "Porque la adherencia de la cubierta es máxima con un 10–20 % de patinamiento y baja cuando la rueda se bloquea; el ABS la mantiene cerca del pico",
        "Porque el ABS usa los frenos traseros más",
        "No frena en menos distancia, sólo permite doblar",
      ],
      correct: 1,
      explain: "La curva de adherencia sube hasta un pico (10–20 % de patinamiento) y baja hacia la rueda bloqueada. Además, bloqueada, la cubierta pierde casi todo el agarre lateral. En ripio suelto la cosa cambia.",
      topic: "ABS",
    },
    {
      q: "Distancia mínima de frenado desde 100 km/h (27,8 m/s) en asfalto mojado con μ = 0,5, sin contar la reacción:",
      opts: ["≈ 28 m", "≈ 44 m", "≈ 79 m", "≈ 160 m"],
      correct: 2,
      explain: "d = v² / (2 · μ · g) = 772 / (2 × 0,5 × 9,81) ≈ 79 m. En seco (μ ≈ 0,9) serían ≈ 44 m; en hielo (μ ≈ 0,1), casi 400 m.",
      topic: "Frenado",
    },
    {
      q: "Una correa poly-V chilla al arrancar en invierno y al prender luces y electroventilador. ¿Cuál es la mejor acción?",
      opts: [
        "Ponerle spray para correas",
        "Verificar tensión y tensor, alineación y estado de la correa (cristalizada, contaminada con aceite o refrigerante)",
        "Ajustarla al máximo posible",
        "Cambiar la batería",
      ],
      correct: 1,
      explain: "Por la fórmula de Euler (F₁ ≤ F₂ · e^μβ), la correa patina si falta tensión o si baja μ. El spray tapa el síntoma y acelera la cristalización; ajustar de más castiga rodamientos.",
      topic: "Correas",
    },
    {
      q: "Un embrague transmite T = μ · F · rₘ · z. Si un retén pierde aceite sobre el disco y μ cae a la mitad, ¿qué pasa?",
      opts: [
        "El embrague pasa la mitad de torque y, si queda por debajo del torque del motor, patina",
        "Nada, el resorte compensa",
        "Engancha más brusco",
        "Se duplica el torque",
      ],
      correct: 0,
      explain: "El torque transmisible es proporcional a μ. Si cae de 0,30 a 0,15, un embrague que pasaba 216 N·m pasa 108: con un motor de 150 N·m, patina (suben las vueltas y el auto no acelera).",
      topic: "Embrague",
    },
    {
      q: "¿Qué sostiene realmente la llanta contra la maza?",
      opts: [
        "Los bulones trabajando al corte",
        "El rozamiento entre llanta y maza, generado por la precarga de los bulones",
        "El centrado de la llanta en la maza",
        "La presión de la cubierta",
      ],
      correct: 1,
      explain: "Es una unión por rozamiento: los bulones aprietan con toneladas de precarga y el rozamiento entre las caras aguanta las fuerzas. Por eso las caras de apoyo tienen que estar limpias, sin óxido ni pintura.",
      topic: "Uniones",
    },
    {
      q: "Bajando de Uspallata a Mendoza con el pie apoyado en el freno todo el tiempo, el auto empieza a frenar menos aunque pises igual. ¿Qué está pasando primero?",
      opts: [
        "Se gastaron las pastillas",
        "Fading: con la temperatura, el coeficiente de rozamiento de las pastillas cae",
        "Falta de aire en las cubiertas",
        "El ABS se desactiva en bajada",
      ],
      correct: 1,
      explain: "Frenar convierte energía de movimiento en calor. En una bajada larga los discos pasan de cientos de grados y el μ de las pastillas baja. Se previene con freno motor y frenadas firmes y cortas.",
      topic: "Frenos",
    },
  ],

  "fis-hidrostatica": [
    {
      q: "Una cubierta inflada a 30 psi, ¿cuántos bar son aproximadamente?",
      opts: ["0,3 bar", "2,1 bar", "3 bar", "30 bar"],
      correct: 1,
      explain: "1 bar ≈ 14,5 psi, así que 30 / 14,5 ≈ 2,07 bar. Regla rápida: 30 psi ≈ 2 bar.",
      topic: "Unidades",
    },
    {
      q: "Con la llave en contacto y el motor parado, en Mendoza (≈ 750 m), ¿qué tiene que marcar el sensor MAP?",
      opts: ["0 kPa", "≈ 35 kPa", "≈ 92 kPa (la presión atmosférica del lugar)", "≈ 101 kPa siempre"],
      correct: 2,
      explain: "El MAP mide presión absoluta. Sin motor girando, en el múltiple hay presión atmosférica: ≈ 92–93 kPa a 750 m (≈ 101 kPa sólo a nivel del mar). Es un buen chequeo rápido del sensor.",
      topic: "Absoluta",
    },
    {
      q: "La bomba de freno tiene un pistón de 4 cm² y la pinza uno de 24 cm². Si la bomba recibe 2.000 N, ¿con cuánta fuerza empuja el pistón de la pinza?",
      opts: ["333 N", "2.000 N", "12.000 N", "48.000 N"],
      correct: 2,
      explain: "p = 2.000 N / 4 cm² = 500 N/cm² (50 bar). Esa presión llega igual a la pinza: F = 500 × 24 = 12.000 N. El pistón de la pinza se mueve 6 veces menos que el de la bomba.",
      topic: "Pascal",
    },
    {
      q: "Después de cambiar un flexible, el pedal queda esponjoso y mejora si bombeás. ¿Por qué?",
      opts: [
        "El flexible nuevo es más blando",
        "Entró aire: el aire se comprime (Boyle) y la bomba gasta su recorrido achicando la burbuja antes de generar presión",
        "El líquido nuevo es más espeso",
        "Las pastillas se desajustaron",
      ],
      correct: 1,
      explain: "El líquido es prácticamente incompresible; el aire no (p · V = constante). Hay que purgar hasta que salga líquido sin burbujas.",
      topic: "Purgado",
    },
    {
      q: "En una bajada larga el pedal se va al piso, y cuando el auto se enfría vuelve a estar normal. ¿Causa más probable?",
      opts: [
        "Bomba de freno con sellos gastados",
        "Vapor lock: el líquido viejo absorbió agua, hierve con el calor de las pinzas y forma burbujas de vapor",
        "Servofreno roto",
        "Pastillas cristalizadas",
      ],
      correct: 1,
      explain: "El líquido de frenos es higroscópico. Con agua, su punto de ebullición baja mucho (un DOT 4 puede pasar de más de 230 °C a unos 155 °C). Se previene cambiándolo cada 2 años y midiéndolo con un probador.",
      topic: "Líquido de frenos",
    },
    {
      q: "Inflás las cubiertas a 30 psi en Mendoza y subís al Cristo Redentor (≈ 3.200 m). Sin contar la temperatura, ¿qué marca el manómetro allá arriba?",
      opts: ["Menos de 30 psi", "30 psi exactos", "Unos 33 psi", "Unos 45 psi"],
      correct: 2,
      explain: "El aire de adentro (presión absoluta) no cambió, pero afuera hay ≈ 235 hPa menos (≈ 3,4 psi). El manómetro mide la diferencia con la atmósfera, así que marca más. No las desinfles arriba.",
      topic: "Absoluta",
    },
    {
      q: "Con el motor apagado pisás el freno varias veces hasta que queda duro, lo dejás pisado y arrancás. El pedal baja un poco solo. ¿Qué indica?",
      opts: [
        "Una fuga en la bomba",
        "Que el servofreno funciona: al entrar el vacío del motor, empieza a ayudar",
        "Aire en el circuito",
        "Que falta líquido",
      ],
      correct: 1,
      explain: "Es la prueba clásica del servo. Si el pedal no baja al arrancar, revisá la manguera de vacío y su válvula de retención.",
      topic: "Servofreno",
    },
  ],

  "fis-flujo": [
    {
      q: "Por una manguera de 32 mm pasa refrigerante a 1,5 m/s y entra en un tubo de 16 mm. ¿A qué velocidad va ahí?",
      opts: ["0,75 m/s", "3 m/s", "6 m/s", "1,5 m/s"],
      correct: 2,
      explain: "Continuidad: A₁ · v₁ = A₂ · v₂. Con la mitad del diámetro, el área es 4 veces menor, así que la velocidad es 4 veces mayor: 6 m/s.",
      topic: "Continuidad",
    },
    {
      q: "¿Qué indica el '5W' de un aceite 5W-30?",
      opts: [
        "Que es para 5 meses de invierno",
        "Su comportamiento en frío: cuanto más bajo el número antes de la W, más fluido en frío y más rápido llega a los metales en el arranque",
        "Su viscosidad a 100 °C",
        "Que tiene 5 % de aditivos",
      ],
      correct: 1,
      explain: "La W es de winter. El segundo número (30) indica la viscosidad a 100 °C. Un 5W-30 y un 10W-30 son igual de espesos en caliente; el 5W es mejor en el arranque en frío.",
      topic: "Viscosidad",
    },
    {
      q: "En un tubo Venturi, si duplicás el caudal de aire, ¿qué pasa con la caída de presión en la garganta?",
      opts: ["Se duplica", "Se cuadruplica", "Se reduce a la mitad", "No cambia"],
      correct: 1,
      explain: "Δp = ½ · ρ · (v₂² − v₁²): va con el cuadrado de la velocidad. Doble de caudal, doble de velocidad, cuatro veces la depresión.",
      topic: "Venturi",
    },
    {
      q: "¿Por qué un carburador necesita un circuito de ralentí aparte del surtidor principal?",
      opts: [
        "Porque en ralentí la nafta está fría",
        "Porque con poco caudal de aire la depresión en el difusor es casi nula y no alcanza para levantar la nafta desde la cuba",
        "Porque el surtidor principal se tapa",
        "Para ahorrar nafta en ruta",
      ],
      correct: 1,
      explain: "La depresión del Venturi crece con el cuadrado del caudal. En ralentí no llega a levantar la nafta los milímetros que hacen falta; el circuito de ralentí toma nafta debajo de la mariposa, donde el vacío es alto.",
      topic: "Carburador",
    },
    {
      q: "Un auto a carburador regulado en Buenos Aires anda 'ahogado' y humea negro en Uspallata. ¿Por qué?",
      opts: [
        "Porque la nafta es distinta en la montaña",
        "Porque el aire es menos denso: entra menos masa de aire pero el carburador entrega casi la misma nafta, y la mezcla se enriquece",
        "Porque hace frío",
        "Porque el filtro de aire está sucio",
      ],
      correct: 1,
      explain: "A igual caudal volumétrico entra menos masa de aire, y el caudal de nafta del chicler cae menos (va con la raíz de la densidad). La inyección electrónica lo corrige midiendo presión o masa de aire.",
      topic: "Altura",
    },
    {
      q: "El aceite caliente (ν ≈ 14 mm²/s) circula a 2 m/s por una galería de 8 mm. ¿Qué régimen tiene?",
      opts: ["Turbulento, Re ≈ 114.000", "Laminar, Re ≈ 1.140", "Turbulento, Re ≈ 11.400", "Laminar, Re ≈ 11"],
      correct: 1,
      explain: "Re = v · D / ν = 2 × 0,008 / 0,000014 ≈ 1.140, por debajo de ≈ 2.300: laminar. El refrigerante en una manguera, en cambio, es turbulento (y eso ayuda a sacar calor).",
      topic: "Reynolds",
    },
    {
      q: "Al auto le falta potencia sólo a fondo y arriba; en el scanner, el MAP a plena carga queda 10 kPa por debajo de la presión atmosférica. ¿Qué sospechás primero?",
      opts: [
        "Un inyector tapado",
        "Una restricción en la admisión: filtro de aire tapado, conducto aplastado o mariposa que no abre del todo",
        "Bujías gastadas",
        "Sensor de temperatura defectuoso",
      ],
      correct: 1,
      explain: "A fondo, el MAP debería quedar a pocos kPa de la presión atmosférica. La pérdida de carga crece con el cuadrado del caudal, por eso una restricción casi no se nota abajo y mucho arriba.",
      topic: "Pérdida de carga",
    },
  ],
};

export default q;
